apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
spec:
  type: NodePort
  selector:
    app: webapp              # routes traffic to pods with this label
  ports:
    - port: 80               # ClusterIP port (internal)
      targetPort: 80         # pod container port
      nodePort: 30081        # external port on every node
