# verify_file.yml
- name: Verify dynamic file
  hosts: all
  tasks:
    - name: Check file
      stat:
        path: "{{ file_name }}"
      register: file_status

    - name: Print result
      debug:
        msg: "File {{ file_name }} exists: {{ file_status.stat.exists }}"
